services:
  api:
    container_name: 'zshop_api'
    image: zshop_api:latest
    ports:
      - "--:8080"
    volumes:
      - logs:/app/logs
      - resources:/app/resources
    environment:
      - AdminPassword=
      - AdminEmail=
      - AdminUserName=
      - SecretKey=
      - SystemEmailPassword=
      - SystemEmailAddress=
      - ZShopCloudinaryApiSecret=
      - ZShopCloudinaryApiKey=
      - ZShopCloudinaryCloundName=
      - ZShopVNPayHashSecret=
      - GoogleClientSecret=
      - GoogleClientId=
      - REDIS_CONNECTION_PASSWORD=
      - ZShopMySQLConnectionString=
    networks:
      - default_net

volumes:
  resources:
  logs:

networks:
  default_net:
    external: true