name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore BE/zshop.sln

    - name: Build
      run: dotnet build BE/zshop.sln --no-restore --configuration Release

    - name: Test (Unit & Integration)
      run: dotnet test BE/zshop.sln --no-build --verbosity normal --configuration Release
